### PR TITLE
Fix NV21 conversion on macos

### PR DESCRIPTION
**Pull request by promag**
Running on macos 10.14.3 the converted images didn't look right. Got them by uncommenting https://github.com/ftylitak/qzxing/blob/b213f9fab3b676a2b94c422587a429e6a75f552f/src/QZXingFilter.cpp#L335-L336

With the change in this PR the converted image is fine. The function `YUV_NV21_TO_RGB` was taken from https://stackoverflow.com/q/12469730.

### CODE REVIEW

**Comment by ftylitak** [comment]
@promag  thank you for your contribution,

Since I do not have access to any macos machine, can you confirm that your solution works properly for: 
 - Qt 5.9.x
 - Qt 5.12.x
 - Qt 5.13.x

If this change is needed only for Qt 5.13.x , you can use the special macro used here:
https://github.com/ftylitak/qzxing/blob/b213f9fab3b676a2b94c422587a429e6a75f552f/src/QZXingFilter.cpp#L249

**Comment by ftylitak** [comment]
@promag since you are available, i would like to ask. 

you have characterized this pull request as WIP. Should I expect more commits to it?

**Comment by promag** [comment]
@ftylitak yes I'm planning to do so. I'll also test as you suggest.

**Comment by promag** [comment]
> Since I do not have access to any macos machine, can you confirm that your solution works properly for:
> 
> * Qt 5.9.x
> * Qt 5.12.x
> * Qt 5.13.x

No longer WIP, rebased and tested with 5.9.0, 5.12.0 and 5.13.0.

**Pull request merged**
