### PR TITLE
Revert cmake dep to be 3.2

### LINKED ISSUE #167: Unnecessary CMake version dependency
The features used in qzxing for the CMake build are quite simple, and it seems the version increase was not necessary. The higher version dependency makes building on Ubuntu 16.04 and other platforms which still have older CMake versions, unnecessarily complex and difficult.

When this change happened, there were also new variables defined in the main `CMakeLists.txt` which are not used anywhere. It seems that perhaps a change in newer CMake which makes specifying full path when adding sources to a target from a sub-directory's `CMakeLists.txt` unnecessary, is perhaps what lead to the new version dependency. Relaxing the dependency and providing the full paths in the sub-directories is possible, though, allowing easy builds on other platforms.

### PR DESCRIPTION
**Pull request by dobey**
The new style Qt5 find_package usage does not require newer CMake, nor
do any of the other CMake commands for qzxing, so go back to only depending
on CMake 3.2, to allow building on Ubuntu 16.04.

Fixes #167

### CODE REVIEW

**Comment by Milerius** [comment]
why this is merged @ftylitak ? This is a terrible Pull request which broke every of your users.

The path on windows using `WIN32_DIR` is likely not working because there is an extra `zxing`, when you have the sources already in the same Directory of `CMakeLists.txt` you don't have to use fancy variables

**Comment by dobey** [comment]
> also next time @dobey don't be a sellfish user, and try to test your stuff EVERYWHERE before sending a pr. and doing modification on extra platform that you are not using.

No need to be rude. I don't use windows. If you have a problem with the merge, then open an issue and tag it in here, and discuss it there. Complain about there not being CI which builds on Windows in all configurations. But don't presume yourself superior to others and come on here calling me selfish and demanding I solve your problems for you.

**Comment by ftylitak** [comment]
@Milerius, @dobey is right. The responsibility on anything that happens here is mine, not on the people that are giving their time to contribute. The fact that I had not tested it on Windows was my mistake and you should have opened an issue to report your opinion there stating also the urgency of your issue. Targeting on individuals in such a way is not acceptable and I hope it will never happen again. 

Regardless, I will soon look at your contributions and proceed with the actions needed.

**Comment by Milerius** [comment]
@dobey @ftylitak we all have stress days :). Sorry for the rude words.

**Comment by ftylitak** [comment]
@Milerius indeed we all do. 

Thank you for pointing out the issue in cmake.

**Pull request merged**
