### PR TITLE
Add ci for windows, linux, android. 

### PR DESCRIPTION
**Pull request by KangLin**
Add ci for windows, linux, android.

appveyor: https://www.appveyor.com/docs/
Travis ci: https://docs.travis-ci.com/

It is found #54 error. See: https://ci.appveyor.com/project/KangLin/qzxing

Appveyor:
Step 1 - Sign in with AppVeyor

Use GitHub or Bitbucket button to sign up with your existing developer account (OAuth) or create an AppVeyor account using your email and password.
Step 2 - Add your project

Authorize GitHub or BitBucket to list your repositories. For open-source project developers who are using the same GitHub account for both personal and private company repositories AppVeyor offers a choice between two scopes: public repositories exclusively or public and private.

For every project AppVeyor will configure webhooks for its repository to automatically start a build when you push the changes. For every private project AppVeyor will add an SSH public key (deployment key) to the clone repository on the build machine.

### CODE REVIEW

**Comment by KangLin** [comment]
In README.md, add Status badges. Please change it to your status badges!

**Comment by KangLin** [comment]
@ftylitak 
The pull request include two part:
1. Fix : INTMAX_MAX undeclared identifier in ratio #54 
2. Added automatic compilation for automatically checking compilation errors

Please you merge it!

**Comment by ftylitak** [comment]
Hello @KangLin,

since the pull request has two parts, i would recommend to split the pull request into two.
I will accept the fix for the INTMAX_MAX, though for the "ci" I need time to review it and I can not promise when I will find the time (hope soon).

Thank you very much for your contribution.

**Comment by KangLin** [comment]
I commited separately, but github merged the two pull requests into one

**Pull request closed without merging**
