### PR TITLE
Remove all custom android stuff

### PR DESCRIPTION
**Pull request by milianw**
The example deploys just fine without all of this. With the custom
stuff, I cannot deploy it to android using a new Qt 5.8 and current
Android SDK/NDK.

Quite frankly, I'm not an Android expert. But I don't get why all this custom code should be required in the first place. Permissions get requested via the manifest, no? Is this all maybe for older Qt/Android versions?

### CODE REVIEW

**Comment by ftylitak** [comment]
Hello @milianw ,

from Android 6 and above, the permissions need to be requested at run time. That is, the application needs to request permission for "dangerous" features that are already declared in the Manifest file. The camera feature is one of the dangerous permissions since it exposes user data to the applicaiton. In that way, the normal pop-up window for permission acceptance will be shown (if the permission was not previously accepted). This is the procedure that needs to be followed according to the [Android standards](https://developer.android.com/training/permissions/requesting.html). If this is not followed, the user must go manually to the security settings of the application and manually grant the needed permissions. 

For the context of this example application i could leave out the correct principles, to keep the code cleaner (maybe), though i prefer to provide the correct way that an end application needs to behave. This is why i will not proceed to remove the Android specific parts. 

Regarding the issue that you mention, can you provide me more information on the failed deployment that you are experiencing? (Exact Android version, error log etc.)

**Comment by milianw** [comment]
Hm, odd - on my laptop I cannot reproduce this issue anymore. I'll try to reproduce it next week on my work desktop machine again, where I initially ran into this.

Hopefully it's just a setup issue

**Comment by ftylitak** [comment]
Most likely you have tried to deploy the application from and an other computer other that the one that you firstly deployed the application. The APK gets self-signed for debug/development purposes using an ID of the deployment machine. If you try to do the same procedure from an other computer you will get the deployment error because of this ID mismatch so the application can not be updated. 

This can be bypassed if you uninstall the application and redeploy it every time you decide to change development machine.

**Comment by ftylitak** [comment]
This pull request will be closed. 
I am getting reports that the Android implementation that contains the permission request procedure has been helpful so this part will be kept. 

@milianw in case you face any new deployment issues you are welcomed to create an issue.

**Comment by milianw** [comment]
yep thanks, and sorry for not getting back to you sooner. I haven't had the time to investigate this deeper, will report an issue the next time I run into it

cheers

**Pull request closed without merging**
